version: '3'

services:
  web:
    build: ./web
    container_name: web
    ports:
      #- "80:80"
      - "443:443"
    environment:
      - APIUSER=guru
      - APIPASS=123456
      - CERTSUBJECT=127.0.0.1.nip.io
      - ENCKEY=$ENCKEY
      - ENCCRT=$ENCCRT


  graphql:
    build: ./api
    container_name: graphql
    environment:
    - GH_TOKEN=$PAT
    - REPO_OWNER=mkol5222
    - REPO_NAME=filex
    - REPO_FILE=policy/somepolicy.json
    - REPO_BRANCH=main
    - REPO_PLAN_BRANCH=plan