version: '3'

services:
  web:
    build: ./web
    container_name: web
    ports:
      #- "80:80"
      - "443:443"
    environment:
      - APIUSER=guru
      - APIPASS=123456
      - CERTSUBJECT=127.0.0.1.nip.io
  api:
    image: httpd
    container_name: api
  graphql:
    build: ./api
    container_name: graphql
    
